apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
spec:
  replicas: 1
  selector:
    matchLabels: ## 通过标签选择器管理POD
      app: trip-service ## 只管理带这个标签的POD
  template: ##指定了POD的蓝图，结构是怎么样的
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
        - name: trip-service
          image: ride-sharing/trip-service
          ports:
            - containerPort: 9093
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: trip-service
  ports:
    - port: 9093
      name: grpc
      targetPort: 9093
  type: ClusterIP
